"""
Bake the eval results into web/static/data.js.

    .venv\\Scripts\\python -m web.build_data

Why this exists: a browser opening index.html from the file system cannot
fetch() a sibling JSON file -- file:// origins are opaque, so the request is
blocked by CORS. A <script src="data.js"> tag is not, so the dashboard reads
its numbers from a global instead.

The result is that the dashboard survives everything: no server, no database,
no model, no network. Re-run this after any `eval/run.py`.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from web.server import dashboard_payload  # noqa: E402

OUT = Path(__file__).resolve().parent / "static" / "data.js"


def main() -> int:
    payload = dashboard_payload()
    OUT.write_text(
        "// GENERATED by `python -m web.build_data` -- do not edit.\n"
        "// Lets index.html render from the file system, with no server.\n"
        f"window.__HARNESS_DATA__ = {json.dumps(payload, indent=1, default=str)};\n",
        encoding="utf-8")

    runs = ", ".join(f"{r['arm']}-{r['provider']} "
                     f"{r['summary']['correct']}/{r['summary']['total']}"
                     for r in payload["runs"])
    print(f"wrote {OUT.relative_to(ROOT)}  ({OUT.stat().st_size / 1024:.0f} KB)")
    print(f"  runs: {runs or '(none -- run eval/run.py first)'}")
    print(f"  questions: {len(payload['questions'])}, defects: {len(payload['defects'])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
